// ======================================================================
// \title  FppConstantsAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FPP constants
// ======================================================================

#ifndef LEDBlinker_Top_FppConstantsAc_HPP
#define LEDBlinker_Top_FppConstantsAc_HPP

#include "FpConfig.hpp"

namespace LEDBlinker {

  namespace Default {

    enum FppConstant_QUEUE_SIZE {
      QUEUE_SIZE = 10
    };

    enum FppConstant_STACK_SIZE {
      STACK_SIZE = 65536
    };

  }

}

#endif
